### ISSUE TITLE
How would one create a correct.yml?

### ISSUE THREAD

**Issue by GantMan** [dkhamsing/readme-correct#1]
The correct.yml file doesn't really help much, unless you know a common problem?  Is that what this is geared towards?

**Comment by dkhamsing** [comment]
Yes you must know a common problem, like a frequent mispeling
What did you have in mind

**Comment by GantMan** [comment]
I found yaspeller after this repo.  It worked nicely for me.   
Perhaps there's a good way to have yaspeller fill the YAML https://github.com/hcodes/yaspeller but for now, I can do it manually.
